# Generated by Django 5.0.14 on 2026-02-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('worker', 'Работник сервисного центра')], default='client', max_length=20, verbose_name='Роль'),
        ),
    ]
