# Generated by Django 5.0.14 on 2026-02-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('supply', 'Поставка'), ('write_off', 'Списание товара'), ('return_supplier', 'Возврат поставщику'), ('inventory', 'Инвентаризация'), ('transfer', 'Перемещение')], max_length=20, verbose_name='Тип операции'),
        ),
    ]
