# Generated by Django 5.0.14 on 2026-02-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_service'),
        ('orders', '0003_alter_order_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.component', verbose_name='Комплектующая'),
        ),
    ]
